### ISSUE TITLE
Move-away from static device list to dynamic device pool

### ISSUE THREAD

**Issue by SrinivasanTarget** [AppiumTestDistribution/AppiumTestDistribution#800]
Currently, we fetch the complete device list upfront and store it in a hashmap well before the execution starts rather than having a dynamic pool of devices so anyone can remove or add a new device during the execution

**Comment by priyankshah217** [comment]
@SrinivasanTarget @saikrishna321 one enhancement would consider like, if during execution if 2 or more tests failed due to device specific issue. ATD just simply remove that device from available list to prevent same failures. Would like to discuss more on that idea. May be redis or distributed cache can be used.

**Comment by WasiqB** [comment]
one idea would be to do health check on device before running the test on that device. and if the check fails, we'll remove that device from the list of runnable devices.

Health check can be:
- Battery check
- Storage check, etc.

**Comment by saikrishna321** [comment]
@priyankshah217 @WasiqB With Appium 2.0 support and with plugin https://github.com/SrinivasanTarget/appium-device-plugin going forward ATD will not maintain the device pool. Plugin will maintain that. 

Can you please create issues here [https://github.com/SrinivasanTarget/appium-device-plugin](url) so we can implement idea regards to device pool list

**Comment by saikrishna321** [comment]
Support added in latest release 13.0.0
